version: '3'
services:
    mariadb:
        build:
            context: ./dockerfiles/mariadb
            dockerfile: ./Dockerfile
        restart: always
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        ports:
            - "3306:3306"
        volumes:
            - ./volumes/mariadb:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: jra
            MYSQL_USER: jra
            MYSQL_PASSWORD: jra
    puppeteer:
        build:
            context: ./dockerfiles/puppeteer
            dockerfile: ./Dockerfile
        volumes:
            - ./volumes/puppeteer:/app
        depends_on:
            - mariadb

