version: '3'
services:
    mariadb:
        image: mariadb:10.4.11-bionic
        restart: always
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        ports:
            - "3306:3306"
        volumes:
            - ./volumes/mariadb/mount:/var/lib/mysql
            - ./volumes/mariadb/initdb:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${NODE_DB_DATABASE}
            MYSQL_USER: ${NODE_DB_USER}
            MYSQL_PASSWORD: ${NODE_DB_PASSWORD}
    puppeteer:
        build:
            context: ./dockerfiles/puppeteer
            dockerfile: ./Dockerfile
        volumes:
            - ./volumes/puppeteer:/app
            - ./dockerfiles/puppeteer:/volume
        env_file: .env
        depends_on:
            - mariadb
        command: /bin/startup.sh
